sudo: required
services:
  - docker

before_install:
  - docker build -t harrychang12/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true harrychang12/react-test npm test -- --coverage

after_success:
  - docker build -t harrychang12/multicontainer-client:latest ./client
  - docker build -t harrychang12/multicontainer-nginx:latest ./nginx
  - docker build -t harrychang12/multicontainer-server:latest ./server
  - docker build -t harrychang12/multicontainer-worker:latest ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push harrychang12/multicontainer-client:latest
  - docker push harrychang12/multicontainer-nginx:latest
  - docker push harrychang12/multicontainer-server:latest
  - docker push harrychang12/multicontainer-worker:latest