sudo: required
services:
  - docker

before_install:
  - docker build -t harrychang12/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true harrychang12/react-test npm test -- --coverage

after_success:
  - docker build -t harrychang12/multicontainer-client:latest ./client
  - docker build -t harrychang12/multicontainer-nginx:latest ./nginx
  - docker build -t harrychang12/multicontainer-server:latest ./server
  - docker build -t harrychang12/multicontainer-worker:latest ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push harrychang12/multicontainer-client:latest
  - docker push harrychang12/multicontainer-nginx:latest
  - docker push harrychang12/multicontainer-server:latest
  - docker push harrychang12/multicontainer-worker:latest

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: multicontainer-aws
  env: MulticontainerAws-env
  bucket_name: elasticbeanstalk-ap-southeast-1-725427206909
  bucket_path: docker-multicontainer
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY